import type { FinancialProfile, PastPurchase, Product } from "./types";

export const DEMO_PRODUCTS: Product[] = [
  {
    id: "smartphone",
    name: "Galaxy S-series 5G (256GB)",
    brand: "Samsung",
    category: "Smartphone",
    price: 34999,
    mrp: 49999,
    typicalPrice: 31200,
    fairPriceLow: 28500,
    fairPriceHigh: 32000,
    refurbPrice: 26999,
    usedPrice: 22000,
    resaleAfter1Year: 21000,
    lifetimeYears: 4,
    refreshSoon: true,
    discountFrequency: "high",
    offerText: "30% OFF · Only 2 left · Sale ends in 10 minutes",
    envImpactNew: "High",
    emoji: "📱",
    specs: ["6.5\" AMOLED 120Hz", "8GB / 256GB", "5000mAh"],
    keywords: ["phone", "mobile", "smartphone", "galaxy", "samsung", "iphone", "5g", "handset"],
  },
  {
    id: "laptop",
    name: "Ryzen 7 Thin & Light Laptop",
    brand: "Lenovo",
    category: "Laptop",
    price: 62999,
    mrp: 79999,
    typicalPrice: 67500,
    fairPriceLow: 62000,
    fairPriceHigh: 70000,
    refurbPrice: 57999,
    usedPrice: 46000,
    repairCost: 7500,
    resaleAfter1Year: 40000,
    lifetimeYears: 5,
    discountFrequency: "medium",
    offerText: "Limited-period festive price",
    envImpactNew: "High",
    emoji: "💻",
    specs: ["Ryzen 7 · 16GB RAM", "1TB SSD", "14\" 2.8K OLED"],
    keywords: ["laptop", "notebook", "macbook", "lenovo", "hp", "dell", "asus", "ultrabook", "ryzen", "intel"],
  },
  {
    id: "headphones",
    name: "WH-1000XM5 Noise Cancelling",
    brand: "Sony",
    category: "Headphones",
    price: 29999,
    mrp: 34990,
    typicalPrice: 28400,
    fairPriceLow: 24000,
    fairPriceHigh: 28000,
    refurbPrice: 19999,
    usedPrice: 16500,
    resaleAfter1Year: 14000,
    lifetimeYears: 4,
    discountFrequency: "high",
    envImpactNew: "Medium",
    emoji: "🎧",
    specs: ["Industry-leading ANC", "30h battery", "Multipoint"],
    keywords: ["headphone", "headphones", "headset", "over-ear", "anc", "sony", "bose", "wh-1000"],
  },
  {
    id: "earbuds",
    name: "True Wireless ANC Earbuds",
    brand: "boAt",
    category: "Earbuds",
    price: 3499,
    mrp: 5990,
    typicalPrice: 2799,
    fairPriceLow: 2200,
    fairPriceHigh: 2900,
    refurbPrice: 2199,
    usedPrice: 1500,
    resaleAfter1Year: 900,
    lifetimeYears: 2,
    discountFrequency: "high",
    offerText: "Flat 42% off · 1000+ bought today",
    envImpactNew: "Medium",
    emoji: "🎵",
    specs: ["ANC 32dB", "40h with case", "Low latency mode"],
    keywords: ["earbuds", "tws", "airpods", "buds", "earphone", "earphones", "boat", "nothing ear"],
  },
  {
    id: "camera",
    name: "Mirrorless Camera + 18-50mm Kit",
    brand: "Canon",
    category: "Camera",
    price: 74999,
    mrp: 89999,
    typicalPrice: 78500,
    fairPriceLow: 72000,
    fairPriceHigh: 80000,
    refurbPrice: 64999,
    usedPrice: 52000,
    rentPerUse: 1500,
    repairCost: 6500,
    resaleAfter1Year: 55000,
    lifetimeYears: 7,
    discountFrequency: "low",
    envImpactNew: "Medium",
    emoji: "📷",
    specs: ["24MP APS-C", "4K 30fps", "In-body stabilisation"],
    keywords: ["camera", "dslr", "mirrorless", "canon", "nikon", "sony alpha", "lens", "photography"],
  },
  {
    id: "projector",
    name: "1080p Smart Home Projector",
    brand: "BenQ",
    category: "Projector",
    price: 12499,
    mrp: 17999,
    typicalPrice: 12100,
    fairPriceLow: 10500,
    fairPriceHigh: 12500,
    refurbPrice: 9499,
    usedPrice: 7500,
    rentPerUse: 700,
    repairCost: 2500,
    resaleAfter1Year: 6500,
    lifetimeYears: 4,
    discountFrequency: "medium",
    offerText: "Deal of the day · 20 people viewing this",
    envImpactNew: "Medium",
    emoji: "📽️",
    specs: ["1080p · 550 ANSI", "Android TV built-in", "Auto keystone"],
    keywords: ["projector", "beamer", "home theatre", "benq", "epson"],
  },
  {
    id: "smartwatch",
    name: "Smartwatch Pro (AMOLED)",
    brand: "Noise",
    category: "Smartwatch",
    price: 8999,
    mrp: 12999,
    typicalPrice: 7600,
    fairPriceLow: 6500,
    fairPriceHigh: 7800,
    refurbPrice: 6299,
    usedPrice: 4800,
    repairCost: 1200,
    resaleAfter1Year: 3200,
    lifetimeYears: 3,
    discountFrequency: "high",
    offerText: "Flat 31% off · Ends tonight",
    envImpactNew: "Medium",
    emoji: "⌚",
    specs: ["1.8\" AMOLED", "BT calling", "7-day battery"],
    keywords: ["smartwatch", "watch", "fitness band", "apple watch", "noise", "boat watch", "wearable"],
  },
  {
    id: "tablet",
    name: "11\" Tablet with Stylus (Wi-Fi)",
    brand: "Xiaomi",
    category: "Tablet",
    price: 24999,
    mrp: 29999,
    typicalPrice: 22800,
    fairPriceLow: 20000,
    fairPriceHigh: 23500,
    refurbPrice: 19499,
    usedPrice: 15500,
    repairCost: 5500,
    resaleAfter1Year: 15000,
    lifetimeYears: 5,
    discountFrequency: "medium",
    envImpactNew: "Medium",
    emoji: "📋",
    specs: ["11\" 144Hz LCD", "8GB / 256GB", "Stylus support"],
    keywords: ["tablet", "ipad", "tab", "xiaomi pad", "stylus", "note taking"],
  },
  {
    id: "tv",
    name: "55\" 4K QLED Smart TV",
    brand: "TCL",
    category: "Television",
    price: 42999,
    mrp: 74999,
    typicalPrice: 39900,
    fairPriceLow: 36000,
    fairPriceHigh: 41000,
    refurbPrice: 33999,
    usedPrice: 25000,
    repairCost: 8000,
    resaleAfter1Year: 26000,
    lifetimeYears: 8,
    discountFrequency: "high",
    offerText: "43% OFF · Big Days Sale · Hurry, few left",
    envImpactNew: "High",
    emoji: "📺",
    specs: ["55\" 4K QLED", "Dolby Vision · Atmos", "Google TV"],
    keywords: ["tv", "television", "led tv", "qled", "smart tv", "tcl", "oled"],
  },
  {
    id: "console",
    name: "Home Gaming Console (1TB)",
    brand: "PlayStation",
    category: "Gaming console",
    price: 49990,
    mrp: 54990,
    typicalPrice: 47500,
    fairPriceLow: 44000,
    fairPriceHigh: 48000,
    refurbPrice: 39999,
    usedPrice: 33000,
    rentPerUse: 500,
    repairCost: 6500,
    resaleAfter1Year: 38000,
    lifetimeYears: 6,
    discountFrequency: "low",
    envImpactNew: "Medium",
    emoji: "🎮",
    specs: ["1TB SSD", "4K 120Hz gaming", "Wireless controller"],
    keywords: ["console", "playstation", "ps5", "xbox", "gaming console", "nintendo", "switch"],
  },
  {
    id: "washingmachine",
    name: "7kg Fully Automatic Washing Machine",
    brand: "LG",
    category: "Washing machine",
    price: 27990,
    mrp: 34990,
    typicalPrice: 26400,
    fairPriceLow: 24500,
    fairPriceHigh: 27000,
    refurbPrice: 21999,
    usedPrice: 15000,
    repairCost: 3500,
    resaleAfter1Year: 17000,
    lifetimeYears: 10,
    discountFrequency: "medium",
    envImpactNew: "High",
    emoji: "🌀",
    specs: ["7kg front load", "5 star rated", "Inverter motor"],
    keywords: ["washing machine", "washer", "front load", "top load", "lg", "whirlpool", "ifb"],
  },
  {
    id: "airconditioner",
    name: "1.5 Ton 5-Star Inverter Split AC",
    brand: "Daikin",
    category: "Air conditioner",
    price: 39990,
    mrp: 52990,
    typicalPrice: 37500,
    fairPriceLow: 35000,
    fairPriceHigh: 38500,
    refurbPrice: 31999,
    usedPrice: 22000,
    repairCost: 4500,
    resaleAfter1Year: 26000,
    lifetimeYears: 10,
    discountFrequency: "high",
    offerText: "Summer sale · Extra ₹2,000 bank cashback · Limited stock",
    envImpactNew: "High",
    emoji: "❄️",
    specs: ["1.5 ton · 5 star", "Copper condenser", "Inverter compressor"],
    keywords: ["ac", "air conditioner", "split ac", "daikin", "voltas", "cooling", "inverter ac"],
  },
  {
    id: "refrigerator",
    name: "260L Double Door Refrigerator",
    brand: "Samsung",
    category: "Refrigerator",
    price: 25490,
    mrp: 32900,
    typicalPrice: 24200,
    fairPriceLow: 22500,
    fairPriceHigh: 24800,
    refurbPrice: 19999,
    usedPrice: 13500,
    repairCost: 3000,
    resaleAfter1Year: 15500,
    lifetimeYears: 12,
    discountFrequency: "medium",
    envImpactNew: "High",
    emoji: "🧊",
    specs: ["260L frost free", "3 star rated", "Convertible freezer"],
    keywords: ["fridge", "refrigerator", "double door", "freezer", "godrej", "haier"],
  },
  {
    id: "cycle",
    name: "Alloy Hybrid Cycle (21-speed)",
    brand: "Btwin",
    category: "Bicycle",
    price: 21999,
    mrp: 25999,
    typicalPrice: 20500,
    fairPriceLow: 18500,
    fairPriceHigh: 21000,
    usedPrice: 12000,
    rentPerUse: 250,
    repairCost: 1500,
    resaleAfter1Year: 14000,
    lifetimeYears: 8,
    discountFrequency: "low",
    envImpactNew: "Low",
    emoji: "🚲",
    specs: ["Alloy frame", "21-speed Shimano", "Disc brakes"],
    keywords: ["cycle", "bicycle", "bike", "btwin", "decathlon", "mtb", "hybrid cycle"],
  },
  {
    id: "sneakers",
    name: "Cushioned Running Sneakers",
    brand: "Nike",
    category: "Footwear",
    price: 7999,
    mrp: 10995,
    typicalPrice: 6800,
    fairPriceLow: 5500,
    fairPriceHigh: 7000,
    usedPrice: 2500,
    repairCost: 600,
    resaleAfter1Year: 2000,
    lifetimeYears: 2,
    discountFrequency: "high",
    offerText: "27% off · Only few sizes left",
    envImpactNew: "Medium",
    emoji: "👟",
    specs: ["Foam midsole", "Breathable mesh", "Everyday running"],
    keywords: ["shoes", "sneakers", "running shoes", "nike", "adidas", "puma", "footwear", "trainers"],
  },
  {
    id: "mixer",
    name: "750W Mixer Grinder (3 Jars)",
    brand: "Preethi",
    category: "Kitchen appliance",
    price: 4499,
    mrp: 6295,
    typicalPrice: 4100,
    fairPriceLow: 3600,
    fairPriceHigh: 4300,
    usedPrice: 1800,
    repairCost: 800,
    resaleAfter1Year: 2200,
    lifetimeYears: 8,
    discountFrequency: "medium",
    envImpactNew: "Low",
    emoji: "🍲",
    specs: ["750W motor", "3 stainless jars", "Overload protection"],
    keywords: ["mixer", "grinder", "mixie", "blender", "kitchen", "preethi", "bajaj", "juicer"],
  },
];

export const DEMO_PROFILE: FinancialProfile = {
  income: 35000,
  essentials: 18000,
  discretionary: 7000,
  savings: 60000,
  goal: "Buy a laptop in 6 months",
  monthlyShopping: 4500,
  demo: true,
};

export const DEMO_HISTORY: PastPurchase[] = [
  { id: "p1", name: "Smartphone (128GB)", category: "Smartphone", price: 45000, monthsAgo: 11 },
  { id: "p2", name: "Wireless headphones", category: "Headphones", price: 3000, monthsAgo: 6 },
  { id: "p3", name: "Smartwatch", category: "Smartwatch", price: 2500, monthsAgo: 4 },
  { id: "p4", name: "Running shoes", category: "Footwear", price: 5000, monthsAgo: 2 },
];

/**
 * Keyword-scored matcher. Works for pasted links, screenshot text, voice
 * transcripts and AI vision labels ("black over-ear headphones, Sony").
 */
export function findDemoProduct(query: string): Product | undefined {
  const q = " " + query.toLowerCase().replace(/[_\-/?=&.]+/g, " ") + " ";
  let best: { product: Product; score: number } | null = null;

  for (const p of DEMO_PRODUCTS) {
    let score = 0;
    if (q.includes(" " + p.id + " ")) score += 6;
    if (q.includes(p.category.toLowerCase())) score += 5;
    if (q.includes(p.brand.toLowerCase())) score += 3;
    if (q.includes(p.name.toLowerCase())) score += 8;
    for (const k of p.keywords ?? []) {
      if (q.includes(" " + k + " ") || q.includes(k + "s ")) score += k.includes(" ") ? 5 : 4;
    }
    if (score > 0 && (!best || score > best.score)) best = { product: p, score };
  }
  return best?.product;
}

/** Best catalog match for financial priors, falling back to the closest price tier. */
export function closestByPrice(price: number): Product {
  return DEMO_PRODUCTS.reduce((a, b) =>
    Math.abs(b.price - price) < Math.abs(a.price - price) ? b : a,
  );
}
